# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: 'ALGORITHM'
  items:
    - label: '✖️ 题目图谱'
      link: '/algorithm/LeetCodeTree'
    - label: '✖️ 数组&堆栈'
      link: '/algorithm/array'
    - label: '✖️ 链表'
      link: '/algorithm/nodeLink'
    - label: '树&图&表'
      link: '/algorithm/treeGraphMap'
    - label: '✖️ 动态规划'
      link: '/algorithm/dp'
    - label: '✖️ 经典算法'
      link: '/algorithm/classicAlg'
    - label: '✖️ 其他题目'
      link: '/algorithm/other'
- label: 'HTML&CSS'
  items:
    - label: '过渡&动画'
      link: '/html&css/transition&animation'
- label: 'Host'
  items:
    - label: '浏览器-基本'
      link: '/host/browser-basic'
    - label: '浏览器-DOM & BOM'
      link: '/host/DOM-BOM'
- label: 'JavaScript'
  items:
    - label: '基础-类型'
      link: '/javascript/types'
    - label: '基础-作用域'
      link: '/javascript/scope'
    - label: '基础-对象'
      link: '/javascript/object'
    - label: 'V8-执行机制'
      link: '/javascript/3.2.2'
- label: 'Frame'
  items:
    - label: 'React-源码'
      link: '/frame/react-source'
    - label: 'Gatsby & GraphQL'
      link: '/frame/gatsby-graphQL'
- label: 'Network'
  items:
    - label: 'HTTP协议'
      link: '/network/http'
- label: 'Other'
  items:
    - label: '代码质量'
      link: '/other/code-quality'
- label: FAQ
  items:
    - label: '资源整理'
      link: '/faq/resource'
    - label: '博客组件'
      link: '/faq/component'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: 'Github'
      link: https://github.com/jeyao
    - label: '语雀'
      link: https://www.yuque.com/yaoqianshu-n5qp5
